apiVersion: v1
kind: Service
metadata:
  name: ty-multiverse-gateway-service
  labels:
    app: ty-multiverse-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: ty-multiverse-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ty-multiverse-gateway
  labels:
    app: ty-multiverse-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ty-multiverse-gateway
  template:
    metadata:
      labels:
        app: ty-multiverse-gateway
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: gateway
        image: papakao/ty-multiverse-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "platform"
        - name: KEYCLOAK_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: KEYCLOAK_AUTH_SERVER_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: PUBLIC_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: PUBLIC_CLIENT_ID
        - name: KEYCLOAK_CREDENTIALS_SECRET
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: KEYCLOAK_CREDENTIALS_SECRET
        - name: PUBLIC_TYMB_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: PUBLIC_TYMB_URL
        - name: PUBLIC_FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: PUBLIC_FRONTEND_URL
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: REDIS_HOST
        - name: REDIS_CUSTOM_PORT
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: REDIS_CUSTOM_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-gateway-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "20m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always

---
apiVersion: v1
kind: Secret
metadata:
  name: ty-multiverse-gateway-secrets
type: Opaque
stringData:
  KEYCLOAK_AUTH_SERVER_URL: "${KEYCLOAK_AUTH_SERVER_URL}"
  PUBLIC_REALM: "${PUBLIC_REALM}"
  PUBLIC_CLIENT_ID: "${PUBLIC_CLIENT_ID}"
  KEYCLOAK_CREDENTIALS_SECRET: "${KEYCLOAK_CREDENTIALS_SECRET}"
  PUBLIC_TYMB_URL: "${PUBLIC_TYMB_URL}"
  PUBLIC_FRONTEND_URL: "${PUBLIC_FRONTEND_URL}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_CUSTOM_PORT: "${REDIS_CUSTOM_PORT}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"

